### ISSUE TITLE
Return CORS headers for Error Responses

### ISSUE THREAD

**Issue by abby-ng** [lawliet89/rowdy#49]

**Comment by lawliet89** [comment]
I think this is a low priority at the moment for a couple of reasons:

1) rowdy does not give really meaningful errors in case of authentication failure (almost always 403) or bad requests (400). This is intentional. We don't really want to give the user any more information other than the operation has failed.

2) The CORS support in rowdy is kind of hacked in at the moment. I'm waiting for [Rocket 0.3 with middleware support to land](https://github.com/SergioBenitez/Rocket/blob/ef2739ee508f35c8859a89c96e5b1cbad2a260d9/lib/src/fairing/mod.rs), and someone (or me) to [write a proper CORS middleware](https://github.com/SergioBenitez/Rocket/issues/25) with this new Middleware support.

So I am parking this aside for now.

**Comment by abby-ng** [comment]
You may enhance the response to be more meaningful with appropriate http error status code in the future. The current situation is the http error status code is returned and in fact it gets the response successfully but masked by the failed to fetch error due to no CORS header error. So I need this to be fixed. Thanks.

**Comment by lawliet89** [comment]
> You may enhance the response to be more meaningful with appropriate http error status code in the future. 

Like I said, it's intentional. So, it's a won't fix.

> The current situation is the http error status code is returned and in fact it gets the response successfully but masked by the failed to fetch error due to no CORS header error. So I need this to be fixed. Thanks.

The application can just treat it as a generic failure, with no further information. That is how most authentication failures work.
